### ISSUE TITLE
Eva Image

### ISSUE THREAD

**Issue by Astraxx04** [Hackman-Genesis/hackmanv6#19]
Eva image height shd be 100vh.

**Comment by giri-madhan** [comment]
I believe it would be better to update the eva image file, as adding '100vh' to the img tag causes the image to appear stretched. Just a suggestion.
![image](https://user-images.githubusercontent.com/87971509/233825564-e9b7ac86-b67b-4808-a363-e2532727c207.png)

**Comment by dz-ai** [comment]
Hi I would like to do it
